openapi: '3.0.0'
info:
  title: 'VERA-Algemeen'
  description: API-specificatie van informatiedomein Algemeen
  termsOfService: 'https://www.stichting-vera.nl/voorwaarden/'
  contact:
    name: 'VERA'
    url: 'https://cora.wikixl.nl/index.php/VERA_Standaard'
    email: 'info@stichting-vera.nl'
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
  version: '4.0'
servers:
  - url: https://algemeen.vera.io:{port}/{basePath}
    description: 'Productieserver'
    variables:
       port:
         enum:
           - '8443'
           - '443'
         default: '443'
       basePath:
         default: v4
tags:
- name: 'ExtraAttributen'
  description: 'Operaties met betrekking tot een ExtraAttribuut'
- name: 'Referentiedata'
  description: 'Operaties met betrekking tot een Referentiedata'
- name: 'Sturingslabels'
  description: 'Operaties met betrekking tot een Sturingslabel'
- name: 'Referentiedata'
  description: 'Operaties met betrekking tot een Referentiedata'
- name: 'Sturingslabels'
  description: 'Operaties met betrekking tot een Sturingslabel'
paths:
  /ping:
    get:
      description: |
        Een ping wordt beantwoord met response code 200
      operationId: ping
      responses:
        '200':
          description: OK
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /extra-attributen:
    get:
      tags:
      - 'ExtraAttributen'
      description: 'Ophalen van ExtraAttributen'
      operationId: 'listExtraAttributen'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/ExtraAttribuut'
      responses:
        '200':
          description: 'ExtraAttribuut response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/ExtraAttribuut'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'ExtraAttributen'
      description: 'Voegt een nieuw(e) ExtraAttribuut toe.'
      operationId: 'createExtraAttribuut'
      requestBody:
        description: 'ExtraAttribuut om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtraAttribuut'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
  /extra-attributen/{id}:
    get:
      tags:
      - 'ExtraAttributen'
      description: 'Retourneert een ExtraAttribuut met de gegeven identifier'
      operationId: 'readExtraAttribuut'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van ExtraAttribuut om op te halen'
        required: true
        schema:
          type: 'string'
      responses:
        '200':
          description: 'ExtraAttribuut response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtraAttribuut'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    put:
      tags:
      - 'ExtraAttributen'
      description: 'Vervangen van een ExtraAttribuut'
      operationId: 'replaceExtraAttribuut'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van ExtraAttribuut om te vervangen'
        required: true
        schema:
          type: 'string'
      requestBody:
        description: 'ExtraAttribuut om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtraAttribuut'
      responses:
        '200':
          description: 'ExtraAttribuut succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'ExtraAttributen'
      description: 'Wijzigen van een ExtraAttribuut'
      operationId: 'updateExtraAttribuut'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van ExtraAttribuut om te wijzigen'
        required: true
        schema:
          type: 'integer'
      requestBody:
        description: 'ExtraAttribuut om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtraAttribuut'
      responses:
        '200':
          description: 'ExtraAttribuut succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /referentiedata:
    get:
      tags:
      - 'Referentiedata'
      description: 'Ophalen van Referentiedata'
      operationId: 'listReferentiedata'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/Referentiedata'
      responses:
        '200':
          description: 'Referentiedata response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Referentiedata'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'Referentiedata'
      description: 'Voegt een nieuw(e) Referentiedata toe.'
      operationId: 'createReferentiedata'
      requestBody:
        description: 'Referentiedata om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
  /referentiedata/{id}:
    get:
      tags:
      - 'Referentiedata'
      description: 'Retourneert een Referentiedata met de gegeven identifier'
      operationId: 'readReferentiedata'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Referentiedata om op te halen'
        required: true
        schema:
          type: 'string'
      responses:
        '200':
          description: 'Referentiedata response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referentiedata'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    put:
      tags:
      - 'Referentiedata'
      description: 'Vervangen van een Referentiedata'
      operationId: 'replaceReferentiedata'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Referentiedata om te vervangen'
        required: true
        schema:
          type: 'string'
      requestBody:
        description: 'Referentiedata om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata'
      responses:
        '200':
          description: 'Referentiedata succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'Referentiedata'
      description: 'Wijzigen van een Referentiedata'
      operationId: 'updateReferentiedata'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Referentiedata om te wijzigen'
        required: true
        schema:
          type: 'integer'
      requestBody:
        description: 'Referentiedata om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata'
      responses:
        '200':
          description: 'Referentiedata succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /sturingslabels:
    get:
      tags:
      - 'Sturingslabels'
      description: 'Ophalen van Sturingslabels'
      operationId: 'listSturingslabels'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/Sturingslabel'
      responses:
        '200':
          description: 'Sturingslabel response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Sturingslabel'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'Sturingslabels'
      description: 'Voegt een nieuw(e) Sturingslabel toe.'
      operationId: 'createSturingslabel'
      requestBody:
        description: 'Sturingslabel om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sturingslabel'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
  /sturingslabels/{id}:
    get:
      tags:
      - 'Sturingslabels'
      description: 'Retourneert een Sturingslabel met de gegeven identifier'
      operationId: 'readSturingslabel'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Sturingslabel om op te halen'
        required: true
        schema:
          type: 'string'
      responses:
        '200':
          description: 'Sturingslabel response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sturingslabel'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    put:
      tags:
      - 'Sturingslabels'
      description: 'Vervangen van een Sturingslabel'
      operationId: 'replaceSturingslabel'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Sturingslabel om te vervangen'
        required: true
        schema:
          type: 'string'
      requestBody:
        description: 'Sturingslabel om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sturingslabel'
      responses:
        '200':
          description: 'Sturingslabel succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'Sturingslabels'
      description: 'Wijzigen van een Sturingslabel'
      operationId: 'updateSturingslabel'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Sturingslabel om te wijzigen'
        required: true
        schema:
          type: 'integer'
      requestBody:
        description: 'Sturingslabel om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sturingslabel'
      responses:
        '200':
          description: 'Sturingslabel succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
security:
  - ApiKeyAuth: []
components:
  headers:
    X-Stuurgegevens-TijdstipBericht:
      schema:
        type: string
        format: data-time
        description: Tijdstip waarop het bericht verzonden is
    X-Stuurgegevens-Referentienummer:
      schema:
        type: string
        format: any
        description: Een unieke code voor correlatie
    X-Stuurgegevens-Zender-Organisatie:
      schema:
        type: string
        format: any
        description: Naam van de verzendende organisatie
    X-Stuurgegevens-Zender-Administratie:
      schema:
        type: string
        format: any
        description: |
          Met het stuurgegeven Administratie kan onderscheid gemaakt worden tussen 
          de verschillende gegevensverzamelingen die de verzendende organisatie beheert
    X-Parameters-Aantal:
      schema:
        type: integer
        description: Totaal aantal gevonden entiteiten
        example: 135
    X-Parameters-AantalPerPagina:
      schema:
        type: integer
        description: Miximum aantal entiteiten per pagina
        example: 20
    X-Parameters-Pagina:
      schema:
        type: integer
        description: Huidige paginanummer
        example: 3
    X-Parameters-PeiltijdstipMaterieel:
      schema:
        type: string
        format: date-time
        description: De peildatum. Indien leeg worden de actuele gegevens opgevraagd
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    NietGeautoriseerd:
      description: API-key ontbreekt of is ongeldig
      headers:
        X-API-KEY:
          schema:
            type: string
  schemas:
    ExtraAttribuut:
      type: object
      properties:
        naam:
          type: 'string'
          format: 'any'
          description: 'De naam van het niet bestaande attribuut. Bijv. Huurprognose.'
        waarde:
          type: 'string'
          format: 'any'
          description: 'De waarde van het niet bestaande attribuut. Bijv. €850,-.'
    Referentiedata:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van de referentiedata of klasse'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        soort:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De soort van het referentiedata item. Bijvoorbeeld nationaliteit.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'De omschrijving van de referentiedata. Bijvoorbeeld De Nederlandse nationaliteit.'
        parent:
          $ref: '#/components/schemas/Referentiedata-sleutels'
          description: 'De bovenliggende referentiedata in het geval er sprake is van een hierarchische relatie tussen referentiedata.'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van het klasse item.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum van het klasse item.'
        sortering:
          type: 'string'
          format: 'any'
          description: 'De sorteervolgorde van de referentiedata anders dan alfabetisch.'
    Referentiedata-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van de referentiedata of klasse'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
    Sturingslabel:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het sturingslabel..'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld DVI2014.'
        soort:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De categorie of groepering van het label. Bijv. dVI samenstelling bezit etc.'
        label:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Het label dat is bepaald op basis van de bijbehorende definitie. Bijv. Zelfstandige huurwoning.'
        datum:
          type: 'string'
          format: 'date'
          description: 'Datum en tijdstip waarop het label is bepaald.'
        bron:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De bron van de definitie van het label. Bijv. dVI 2014, CORA etc.'
    Sturingslabel-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het sturingslabel..'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld DVI2014.'
    Foutbericht:
      type: 'object'
      properties:
        code:
          type: 'string'
        omschrijving:
          type: 'string'

