openapi: '3.0.0'
info:
  title: 'VERA'
  description: 'API-specificatie van het horizontale gegevensmodel'
  termsOfService: 'https://www.stichting-vera.nl/voorwaarden/'
  contact:
    name: 'VERA'
    url: 'https://www.stichting-vera.nl/'
    email: 'info@stichting-vera.nl'
  license:
    name: 'General Public License (GPL)'
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
  version: '4.0.3'
servers:
  - url: https://vera.vera.io:{port}/{basePath}
    description: 'Productieserver'
    variables:
       port:
         enum:
           - '8443'
           - '443'
         default: '443'
       basePath:
         default: v4
tags:
- name: 'Resources'
  description: 'Operaties met betrekking tot entiteiten in dit informatiedomein'
paths:
  /referentiedata:
    get:
      tags:
      - 'Resources'
      description: 'Ophalen van referentiedata'
      operationId: 'readReferentiedata-restricted'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/Referentiedata-restricted'
      responses:
        '200':
          description: 'Referentiedata-restricted response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Referentiedata-restricted'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'Resources'
      description: 'Voegt een nieuw(e) Referentiedata-restricted toe.'
      operationId: 'createReferentiedata-restricted'
      requestBody:
        description: 'Referentiedata-restricted om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata-restricted'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
    put:
      tags:
      - 'Resources'
      description: 'Vervangen van een Referentiedata-restricted'
      operationId: 'replaceReferentiedata-restricted'
      requestBody:
        description: 'Referentiedata-restricted om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata-restricted'
      responses:
        '200':
          description: 'Referentiedata-restricted succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'Resources'
      description: 'Wijzigen van een Referentiedata-restricted'
      operationId: 'modifyReferentiedata-restricted'
      requestBody:
        description: 'Referentiedata-restricted om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata-restricted'
      responses:
        '200':
          description: 'Referentiedata-restricted succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /referentiedata/{id}:
    get:
      tags:
      - 'Resources'
      description: 'Retourneert een Referentiedata-restricted met de gegeven identifier'
      operationId: 'findReferentiedata-restrictedById'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Referentiedata-restricted om op te halen'
        required: true
        schema:
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'Referentiedata-restricted response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referentiedata-restricted'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /referentiedata:
    get:
      tags:
      - 'Resources'
      description: 'Ophalen van referentiedata'
      operationId: 'readReferentiedata'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/Referentiedata'
      responses:
        '200':
          description: 'Referentiedata response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Referentiedata'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'Resources'
      description: 'Voegt een nieuw(e) Referentiedata toe.'
      operationId: 'createReferentiedata'
      requestBody:
        description: 'Referentiedata om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
    put:
      tags:
      - 'Resources'
      description: 'Vervangen van een Referentiedata'
      operationId: 'replaceReferentiedata'
      requestBody:
        description: 'Referentiedata om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata'
      responses:
        '200':
          description: 'Referentiedata succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'Resources'
      description: 'Wijzigen van een Referentiedata'
      operationId: 'modifyReferentiedata'
      requestBody:
        description: 'Referentiedata om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referentiedata'
      responses:
        '200':
          description: 'Referentiedata succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /referentiedata/{id}:
    get:
      tags:
      - 'Resources'
      description: 'Retourneert een Referentiedata met de gegeven identifier'
      operationId: 'findReferentiedataById'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Referentiedata om op te halen'
        required: true
        schema:
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'Referentiedata response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referentiedata'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /sturingslabels:
    get:
      tags:
      - 'Resources'
      description: 'Ophalen van sturingslabels'
      operationId: 'readSturingslabel'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/Sturingslabel'
      responses:
        '200':
          description: 'Sturingslabel response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Sturingslabel'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'Resources'
      description: 'Voegt een nieuw(e) Sturingslabel toe.'
      operationId: 'createSturingslabel'
      requestBody:
        description: 'Sturingslabel om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sturingslabel'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
    put:
      tags:
      - 'Resources'
      description: 'Vervangen van een Sturingslabel'
      operationId: 'replaceSturingslabel'
      requestBody:
        description: 'Sturingslabel om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sturingslabel'
      responses:
        '200':
          description: 'Sturingslabel succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'Resources'
      description: 'Wijzigen van een Sturingslabel'
      operationId: 'modifySturingslabel'
      requestBody:
        description: 'Sturingslabel om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sturingslabel'
      responses:
        '200':
          description: 'Sturingslabel succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /sturingslabels/{id}:
    get:
      tags:
      - 'Resources'
      description: 'Retourneert een Sturingslabel met de gegeven identifier'
      operationId: 'findSturingslabelById'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Sturingslabel om op te halen'
        required: true
        schema:
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'Sturingslabel response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sturingslabel'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
security:
  - basicAuth: []
components:
  headers:
    X_Pagination_Page:
      schema:
        type: integer
        description: Huidige pagina.
        example: 3
    X_Pagination_Limit:
      schema:
        type: integer
        description: Aantal resultaten per pagina.
        example: 20
    X_Stuurgegevens_TijdstipBericht:
      schema:
        type: string
        format: data-time
        description: Tijdstip waarop het bericht verzonden is
    X_Stuurgegevens_Referentienummer:
      schema:
        type: string
        format: any
        description: Een unieke code voor correlatie
    X_Stuurgegevens_Zender:
      schema:
        type: string
        format: any
        description: Identificatie van de verzendende organisatie
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    NietGeautoriseerd:
      description: Authenticatie-informatie ontbreekt of is ongeldig
      headers:
        WWW_Authenticate:
          schema:
            type: string
  schemas:
    Referentiedata-restricted:
      type: object
      properties:
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
        soort:
          $ref: '#/components/schemas/Referentiedata-restricted'
          description: 'De soort van het referentiedata item. Bijvoorbeeld nationaliteit.'
        parent:
          $ref: '#/components/schemas/Referentiedata-restricted'
          description: 'De bovenliggende referentiedata in het geval er sprake is van een hierarchische relatie tussen referentiedata.'
        sortering:
          type: 'string'
          format: 'any'
          description: 'De sorteervolgorde van de referentiedata anders dan alfabetisch.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Referentiedata:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van de referentiedata of klasse'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        soort:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De soort van het referentiedata item. Bijvoorbeeld nationaliteit.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'De omschrijving van de referentiedata. Bijvoorbeeld De Nederlandse nationaliteit.'
        parent:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De bovenliggende referentiedata in het geval er sprake is van een hierarchische relatie tussen referentiedata.'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van het klasse item.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum van het klasse item.'
        sortering:
          type: 'string'
          format: 'any'
          description: 'De sorteervolgorde van de referentiedata anders dan alfabetisch.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Sturingslabel:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het sturingslabel..'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld DVI2014.'
        soort:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De categorie of groepering van het label. Bijv. dVI samenstelling bezit etc.'
        label:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Het label dat is bepaald op basis van de bijbehorende definitie. Bijv. Zelfstandige huurwoning.'
        datum:
          type: 'string'
          format: 'date'
          description: 'Datum en tijdstip waarop het label is bepaald.'
        bron:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De bron van de definitie van het label. Bijv. dVI 2014, CORA etc.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Referentiedata-restricted-sleutels:
      type: object
      properties:
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
    Referentiedata-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van de referentiedata of klasse'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
    Sturingslabel-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het sturingslabel..'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld DVI2014.'
    Foutbericht:
      type: 'object'
      properties:
        code:
          type: 'string'
        omschrijving:
          type: 'string'
    ExtraAttributen:
      type: 'object'
      properties:
        sleutel:
          type: 'string'
        waarde:
          type: 'string'
