openapi: '3.0.0'
info:
  title: 'Beheer Vastgoedegevens'
  description: 'API-specificatie van procesketengegevensmodel BVG'
  termsOfService: 'https://www.stichting-vera.nl/voorwaarden/'
  contact:
    name: 'VERA'
    url: 'https://www.stichting-vera.nl/'
    email: 'info@stichting-vera.nl'
  license:
    name: 'General Public License (GPL)'
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
  version: '1.0.3'
servers:
  - url: https://bvg.vera.io:{port}/{basePath}
    description: 'Productieserver'
    variables:
       port:
         enum:
           - '8443'
           - '443'
         default: '443'
       basePath:
         default: v1
tags:
- name: 'WoningwaarderingResultaten'
  description: 'Operaties met betrekking tot woningwaarderingresultaten'
paths:
  /woningwaardering-resultaten:
    get:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Ophalen van woningwaarderingresultaten'
      operationId: 'readwoningwaarderingresultaten'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '200':
          description: 'WoningwaarderingResultaat response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Voegt een nieuw(e) WoningwaarderingResultaat toe.'
      operationId: 'createWoningwaarderingResultaat'
      requestBody:
        description: 'WoningwaarderingResultaat om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
    put:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Vervangen van een WoningwaarderingResultaat'
      operationId: 'replaceWoningwaarderingResultaat'
      requestBody:
        description: 'WoningwaarderingResultaat om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '200':
          description: 'WoningwaarderingResultaat succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Wijzigen van een WoningwaarderingResultaat'
      operationId: 'modifyWoningwaarderingResultaat'
      requestBody:
        description: 'WoningwaarderingResultaat om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '200':
          description: 'WoningwaarderingResultaat succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /woningwaardering-resultaten/{id}:
    get:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Retourneert een WoningwaarderingResultaat met de gegeven identifier'
      operationId: 'findWoningwaarderingResultaatById'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van WoningwaarderingResultaat om op te halen'
        required: true
        schema:
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'WoningwaarderingResultaat response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
security:
  - basicAuth: []
components:
  headers:
    X_Pagination_Page:
      schema:
        type: integer
        description: Huidige pagina.
        example: 3
    X_Pagination_Limit:
      schema:
        type: integer
        description: Aantal resultaten per pagina.
        example: 20
    X_Stuurgegevens_TijdstipBericht:
      schema:
        type: string
        format: data-time
        description: Tijdstip waarop het bericht verzonden is
    X_Stuurgegevens_Referentienummer:
      schema:
        type: string
        format: any
        description: Een unieke code voor correlatie
    X_Stuurgegevens_Zender:
      schema:
        type: string
        format: any
        description: Identificatie van de verzendende organisatie
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    NietGeautoriseerd:
      description: Authenticatie-informatie ontbreekt of is ongeldig
      headers:
        WWW_Authenticate:
          schema:
            type: string
  schemas:
    WoningwaarderingResultaten-Woningwaardering:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De datum waarop het woning waardering  onderdeel in gaat of is ingegaan.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De datum waarop het woningwaardering onderdeel niet meer van toepassing is.'
        criterium:
          $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingCriterium'
          description: 'De omschrijving van het woningwaardering onderdeel.'
        aantal:
          type: 'number'
          format: 'float'
          description: 'Het aantal van de opgegeven meeteenheid van de bijbehorende woningwaardering criterium.'
        punten:
          type: 'number'
          format: 'float'
          description: 'Het aantal woningwaarderingsstelsel punten dat is toegekend.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    WoningwaarderingResultaten-WoningwaarderingCriterium:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        naam:
          type: 'string'
          format: 'any'
          description: 'De naam van het woningwaardering element.'
        meeteenheid:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De meeteenheid waarmee het criterium wordt aangeduid.'
        stelsel:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Het woningwaardering stelsel bevat een apart puntensystemen voor de eenheidssoorten zelfstandige woningen, kamers, woonwagens en woonwagenstandplaatsen. Dit attribuut geeft het toe te passen puntensysteem aan.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Referentiedata:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van de referentiedata of klasse'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        soort:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De soort van het referentiedata item. Bijvoorbeeld nationaliteit.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'De omschrijving van de referentiedata. Bijvoorbeeld De Nederlandse nationaliteit.'
        parent:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De bovenliggende referentiedata in het geval er sprake is van een hierarchische relatie tussen referentiedata.'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van het klasse item.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum van het klasse item.'
        sortering:
          type: 'string'
          format: 'any'
          description: 'De sorteervolgorde van de referentiedata anders dan alfabetisch.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    WoningwaarderingResultaten-WoningwaarderingCriteriumGroep:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        naam:
          type: 'string'
          format: 'any'
          description: 'De naam van de groep.'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'De omschrijving van de groep.'
        stelsel:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Het woningwaardering stelsel bevat een apart puntensystemen voor de eenheidssoorten zelfstandige woningen, kamers, woonwagens en woonwagenstandplaatsen. Dit attribuut geeft het toe te passen puntensysteem aan.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    WoningwaarderingResultaten-WoningwaarderingGroep:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van de woningwaardering groep.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum waarop de waarop de woningwaardering niet meer geldig is.'
        criteriumGroep:
          $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingCriteriumGroep'
          description: 'De woningwaardering criterium groep behorend bij de woningwaardering groep.'
        punten:
          type: 'number'
          format: 'float'
          description: 'Het aantal woningwaarderingsstelsel punten dat is toegekend.'
        woningwaarderingen:
          description: 'De woningwaarderingen behorend bij de woningwaardering groep.'
          type: array
          items:
            $ref: '#/components/schemas/WoningwaarderingResultaten-Woningwaardering'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    WoningwaarderingResultaten-WoningwaarderingResultaat:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van de woningwaardering puntentotaal.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum waarop de waarop de woningwaardering niet meer geldig is.'
        eenheid:
          type: 'string'
          format: 'uri'
          description: 'Referentie naar Eenheid in de vorm: vera/v4/eenheden/12345'
        punten:
          type: 'number'
          format: 'float'
          description: 'Het aantal woningwaarderingsstelsel punten dat is toegekend.'
        maximaleHuur:
          type: 'number'
          format: 'float'
          description: 'De maximaal redelijke huur in euro"s die geregistreerd staat bij de eenheid. De maximale huur is de huurprijs die gevraagd kan worden voor de eenheid op basis van de woningwaarderingspunten.'
        groepen:
          description: 'De woningwaarderingenGroep behorend bij het woningwaardering puntentotaal.'
          type: array
          items:
            $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingGroep'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    WoningwaarderingResultatenWoningwaardering-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    WoningwaarderingResultatenWoningwaarderingCriterium-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    WoningwaarderingResultatenWoningwaarderingCriteriumGroep-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    WoningwaarderingResultatenWoningwaarderingGroep-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    WoningwaarderingResultatenWoningwaarderingResultaat-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    Foutbericht:
      type: 'object'
      properties:
        code:
          type: 'string'
        omschrijving:
          type: 'string'
    ExtraAttributen:
      type: 'object'
      properties:
        sleutel:
          type: 'string'
        waarde:
          type: 'string'
