openapi: '3.0.0'
info:
  title: 'Incasso'
  description: 'API-specificatie van procesketengegevensmodel INC'
  termsOfService: 'https://www.stichting-vera.nl/voorwaarden/'
  contact:
    name: 'VERA'
    url: 'https://www.stichting-vera.nl/'
    email: 'info@stichting-vera.nl'
  license:
    name: 'General Public License (GPL)'
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
  version: '1.0.3'
servers:
  - url: https://inc.vera.io:{port}/{basePath}
    description: 'Productieserver'
    variables:
       port:
         enum:
           - '8443'
           - '443'
         default: '443'
       basePath:
         default: v1
tags:
- name: 'Betalingsregelingen'
  description: 'Operaties met betrekking tot betalingsregelingen'
paths:
  /betalingsregelingen:
    get:
      tags:
      - 'Betalingsregelingen'
      description: 'Ophalen van betalingsregelingen'
      operationId: 'readBetalingsregeling'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/Betalingsregelingen-Betalingsregeling'
      responses:
        '200':
          description: 'Betalingsregeling response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Betalingsregelingen-Betalingsregeling'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'Betalingsregelingen'
      description: 'Voegt een nieuw(e) Betalingsregeling toe.'
      operationId: 'createBetalingsregeling'
      requestBody:
        description: 'Betalingsregeling om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Betalingsregelingen-Betalingsregeling'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
    put:
      tags:
      - 'Betalingsregelingen'
      description: 'Vervangen van een Betalingsregeling'
      operationId: 'replaceBetalingsregeling'
      requestBody:
        description: 'Betalingsregeling om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Betalingsregelingen-Betalingsregeling'
      responses:
        '200':
          description: 'Betalingsregeling succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'Betalingsregelingen'
      description: 'Wijzigen van een Betalingsregeling'
      operationId: 'modifyBetalingsregeling'
      requestBody:
        description: 'Betalingsregeling om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Betalingsregelingen-Betalingsregeling'
      responses:
        '200':
          description: 'Betalingsregeling succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
  /betalingsregelingen/{id}:
    get:
      tags:
      - 'Betalingsregelingen'
      description: 'Retourneert een Betalingsregeling met de gegeven identifier'
      operationId: 'findBetalingsregelingById'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van Betalingsregeling om op te halen'
        required: true
        schema:
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'Betalingsregeling response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Betalingsregelingen-Betalingsregeling'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
security:
  - basicAuth: []
components:
  headers:
    X_Pagination_Page:
      schema:
        type: integer
        description: Huidige pagina.
        example: 3
    X_Pagination_Limit:
      schema:
        type: integer
        description: Aantal resultaten per pagina.
        example: 20
    X_Stuurgegevens_TijdstipBericht:
      schema:
        type: string
        format: data-time
        description: Tijdstip waarop het bericht verzonden is
    X_Stuurgegevens_Referentienummer:
      schema:
        type: string
        format: any
        description: Een unieke code voor correlatie
    X_Stuurgegevens_Zender:
      schema:
        type: string
        format: any
        description: Identificatie van de verzendende organisatie
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    NietGeautoriseerd:
      description: Authenticatie-informatie ontbreekt of is ongeldig
      headers:
        WWW_Authenticate:
          schema:
            type: string
  schemas:
    Betalingsregelingen-Betaalgegeven:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        rekeningnummer:
          type: 'string'
          format: 'any'
          description: 'Het rekeningnummer.'
        relatie:
          type: 'string'
          format: 'uri'
          description: 'Referentie naar Relatie in de vorm: vera/v4/relaties/12345'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Betalingsregelingen-Betalingsregeling:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'Omschrijving van het gegeven.'
        status:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Status van de betalingsregeling. Voorbeeld: actief, bevroren, geannuleerd, enzovoort.'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'Datum waarop de regeling is of wordt gestart.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'Datum waarop de regeling is of wordt beëindigd.'
        debiteur:
          type: 'string'
          format: 'uri'
          description: 'Referentie naar Debiteur in de vorm: vera/v4/debiteuren/12345'
        bedrag:
          type: 'number'
          format: 'float'
          description: 'Het initiele bedrag van de betalingsregeling.'
        saldo:
          type: 'number'
          format: 'float'
          description: 'Het saldo of openstaande bedrag van de betalingsregeling.'
        betaalgegeven:
          $ref: '#/components/schemas/Betalingsregelingen-Betaalgegeven'
          description: 'Betaalgegeven (rekeningnummer) van de gekoppelde relatie.'
        termijnenAantal:
          type: 'number'
          format: 'float'
          description: 'Het aantal termijnen waaruit de betalingsregeling bestaat.'
        eindeReden:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Reden dat de betalingsregeling is beëindigd. Voorbeeld: voldaan, enzovoort.'
        prolongatieInterval:
          type: 'string'
          format: 'date-time'
          description: 'De interval die aangeeft na hoeveel tijd er wordt geprolongeerd op de betalingsregeling.'
        boekingen:
          description: 'De boekingen behorende bij de betalingsregeling.'
          type: array
          items:
            $ref: '#/components/schemas/Betalingsregelingen-Boeking'
        termijnen:
          description: 'De betalingsregeling termijnen behorende bij de betalingsregeling.'
          type: array
          items:
            $ref: '#/components/schemas/Betalingsregelingen-BetalingsregelingTermijn'
        overeenkomst:
          type: 'string'
          format: 'uri'
          description: 'Referentie naar Overeenkomst in de vorm: vera/v4/overeenkomsten/12345'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Referentiedata:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van de referentiedata of klasse'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        soort:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De soort van het referentiedata item. Bijvoorbeeld nationaliteit.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'De omschrijving van de referentiedata. Bijvoorbeeld De Nederlandse nationaliteit.'
        parent:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De bovenliggende referentiedata in het geval er sprake is van een hierarchische relatie tussen referentiedata.'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van het klasse item.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum van het klasse item.'
        sortering:
          type: 'string'
          format: 'any'
          description: 'De sorteervolgorde van de referentiedata anders dan alfabetisch.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Betalingsregelingen-BetalingsregelingTermijn:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'Omschrijving van het gegeven.'
        status:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Status van de termijn, bv. openstaand, betaald.'
        datum:
          type: 'string'
          format: 'date'
          description: 'Datum waarop de termijn betaald is.'
        vervaldatum:
          type: 'string'
          format: 'date'
          description: 'Vervaldatum van de termijn.'
        bedrag:
          type: 'number'
          format: 'float'
          description: 'Initiële bedrag van de termijn.'
        saldo:
          type: 'number'
          format: 'float'
          description: 'Het saldo of openstaande bedrag van de termijn.'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    Betalingsregelingen-Boeking:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        overeenkomst:
          type: 'string'
          format: 'uri'
          description: 'Referentie naar Overeenkomst in de vorm: vera/v4/overeenkomsten/12345'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttributen'
    BetalingsregelingenBetaalgegeven-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        rekeningnummer:
          type: 'string'
          format: 'any'
          description: 'Het rekeningnummer.'
    BetalingsregelingenBetalingsregeling-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    BetalingsregelingenBetalingsregelingTermijn-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    BetalingsregelingenBoeking-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    Foutbericht:
      type: 'object'
      properties:
        code:
          type: 'string'
        omschrijving:
          type: 'string'
    ExtraAttributen:
      type: 'object'
      properties:
        sleutel:
          type: 'string'
        waarde:
          type: 'string'
