openapi: '3.0.0'
info:
  title: 'VERA-BVG'
  description: API-specificatie van ketenproces "Beheer Vastgoedegevens". Deze specificatie is gebaseerd op VERA versie 4.0
  termsOfService: 'https://www.stichting-vera.nl/voorwaarden/'
  contact:
    name: 'VERA'
    url: 'https://cora.wikixl.nl/index.php/VERA_Standaard'
    email: 'info@stichting-vera.nl'
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
  version: '1.0'
servers:
  - url: https://bvg.vera.io:{port}/{basePath}
    description: 'Productieserver'
    variables:
       port:
         enum:
           - '8443'
           - '443'
         default: '443'
       basePath:
         default: v1
tags:
- name: 'WoningwaarderingResultaten'
  description: 'Operaties met betrekking tot een WoningwaarderingResultaat'
paths:
  /woningwaardering-resultaten:
    get:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Ophalen van WoningwaarderingResultaten'
      operationId: 'listWoningwaarderingResultaten'
      parameters:
      - name: 'params'
        in: 'query'
        style: 'form'
        explode: true
        schema:
          $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '200':
          description: 'WoningwaarderingResultaat response'
          content:
            'application/json':
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Foutbericht'
    post:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Voegt een nieuw(e) WoningwaarderingResultaat toe.'
      operationId: 'createWoningwaarderingResultaat'
      requestBody:
        description: 'WoningwaarderingResultaat om toe te voegen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        '405':
          description: 'Foutieve invoer'
  /woningwaardering-resultaten/{id}:
    get:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Retourneert een WoningwaarderingResultaat met de gegeven identifier'
      operationId: 'readWoningwaarderingResultaat'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van WoningwaarderingResultaat om op te halen'
        required: true
        schema:
          type: 'string'
      responses:
        '200':
          description: 'WoningwaarderingResultaat response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    put:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Vervangen van een WoningwaarderingResultaat'
      operationId: 'replaceWoningwaarderingResultaat'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van WoningwaarderingResultaat om te vervangen'
        required: true
        schema:
          type: 'string'
      requestBody:
        description: 'WoningwaarderingResultaat om te vervangen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '200':
          description: 'WoningwaarderingResultaat succesvol vervangen'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
    patch:
      tags:
      - 'WoningwaarderingResultaten'
      description: 'Wijzigen van een WoningwaarderingResultaat'
      operationId: 'updateWoningwaarderingResultaat'
      parameters:
      - name: 'id'
        in: 'path'
        description: 'Id van WoningwaarderingResultaat om te wijzigen'
        required: true
        schema:
          type: 'integer'
      requestBody:
        description: 'WoningwaarderingResultaat om te wijzigen'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingResultaat'
      responses:
        '200':
          description: 'WoningwaarderingResultaat succesvol gewijzigd'
        '401':
           $ref: '#/components/responses/NietGeautoriseerd'
        default:
          description: 'Onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foutbericht'
security:
  - ApiKeyAuth: []
components:
  headers:
    X-Stuurgegevens-TijdstipBericht:
      schema:
        type: string
        format: data-time
        description: Tijdstip waarop het bericht verzonden is
    X-Stuurgegevens-Referentienummer:
      schema:
        type: string
        format: any
        description: Een unieke code voor correlatie
    X-Stuurgegevens-Zender-Organisatie:
      schema:
        type: string
        format: any
        description: Naam van de verzendende organisatie
    X-Stuurgegevens-Zender-Administratie:
      schema:
        type: string
        format: any
        description: |
          Met het stuurgegeven Administratie kan onderscheid gemaakt worden tussen 
          de verschillende gegevensverzamelingen die de verzendende organisatie beheert
    X-Parameters-Aantal:
      schema:
        type: integer
        description: Totaal aantal gevonden entiteiten
        example: 135
    X-Parameters-AantalPerPagina:
      schema:
        type: integer
        description: Miximum aantal entiteiten per pagina
        example: 20
    X-Parameters-Pagina:
      schema:
        type: integer
        description: Huidige paginanummer
        example: 3
    X-Parameters-PeiltijdstipMaterieel:
      schema:
        type: string
        format: date-time
        description: De peildatum. Indien leeg worden de actuele gegevens opgevraagd
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    NietGeautoriseerd:
      description: API-key ontbreekt of is ongeldig
      headers:
        X-API-KEY:
          schema:
            type: string
  schemas:
    WoningwaarderingResultaten-Woningwaardering:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De datum waarop het woning waardering  onderdeel in gaat of is ingegaan.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De datum waarop het woningwaardering onderdeel niet meer van toepassing is.'
        criterium:
          $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingCriterium'
          description: 'De omschrijving van het woningwaardering onderdeel.'
        aantal:
          type: 'number'
          format: 'float'
          description: 'Het aantal van de opgegeven meeteenheid van de bijbehorende woningwaardering criterium.'
        punten:
          type: 'number'
          format: 'float'
          description: 'Het aantal woningwaarderingsstelsel punten dat is toegekend.'
    WoningwaarderingResultaten-WoningwaarderingCriterium:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        naam:
          type: 'string'
          format: 'any'
          description: 'De naam van het woningwaardering element.'
        meeteenheid:
          $ref: '#/components/schemas/Referentiedata'
          description: 'De meeteenheid waarmee het criterium wordt aangeduid.'
        stelsel:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Het woningwaardering stelsel bevat een apart puntensystemen voor de eenheidssoorten zelfstandige woningen, kamers, woonwagens en woonwagenstandplaatsen. Dit attribuut geeft het toe te passen puntensysteem aan.'
    Referentiedata:
      type: object
      properties:
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken) Bijvoorbeeld NL.'
        naam:
          type: 'string'
          format: 'any'
          description: 'De te tonen waarde van het referentiedata item. Bijvoorbeeld Nederlandse.'
    WoningwaarderingResultaten-WoningwaarderingCriteriumGroep:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        naam:
          type: 'string'
          format: 'any'
          description: 'De naam van de groep.'
        omschrijving:
          type: 'string'
          format: 'any'
          description: 'De omschrijving van de groep.'
        stelsel:
          $ref: '#/components/schemas/Referentiedata'
          description: 'Het woningwaardering stelsel bevat een apart puntensystemen voor de eenheidssoorten zelfstandige woningen, kamers, woonwagens en woonwagenstandplaatsen. Dit attribuut geeft het toe te passen puntensysteem aan.'
    WoningwaarderingResultaten-WoningwaarderingGroep:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van de woningwaardering groep.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum waarop de waarop de woningwaardering niet meer geldig is.'
        criteriumGroep:
          $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingCriteriumGroep'
          description: 'De woningwaardering criterium groep behorend bij de woningwaardering groep.'
        punten:
          type: 'number'
          format: 'float'
          description: 'Het aantal woningwaarderingsstelsel punten dat is toegekend.'
        woningwaarderingen:
          description: 'De woningwaarderingen behorend bij de woningwaardering groep.'
          type: array
          items:
            $ref: '#/components/schemas/WoningwaarderingResultaten-Woningwaardering'
    WoningwaarderingResultaten-WoningwaarderingResultaat:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
        begindatum:
          type: 'string'
          format: 'date'
          description: 'De begindatum van de woningwaardering puntentotaal.'
        einddatum:
          type: 'string'
          format: 'date'
          description: 'De einddatum waarop de waarop de woningwaardering niet meer geldig is.'
        eenheid:
          $ref: '#/components/schemas/Eenheid-sleutels'
          description: 'De eenheid behorend bij de woningwaardering.'
        punten:
          type: 'number'
          format: 'float'
          description: 'Het aantal woningwaarderingsstelsel punten dat is toegekend.'
        maximaleHuur:
          type: 'number'
          format: 'float'
          description: 'De maximaal redelijke huur in euro"s die geregistreerd staat bij de eenheid. De maximale huur is de huurprijs die gevraagd kan worden voor de eenheid op basis van de woningwaarderingspunten.'
        groepen:
          description: 'De woningwaarderingenGroep behorend bij het woningwaardering puntentotaal.'
          type: array
          items:
            $ref: '#/components/schemas/WoningwaarderingResultaten-WoningwaarderingGroep'
        extra-attributen:
          description: 'Toegevoegde sleutel/waarde-paren'
          type: array
          items:
            $ref: '#/components/schemas/ExtraAttribuut'
    Eenheid-sleutels:
      type: object
      properties:
        id:
          type: 'string'
          format: 'any'
          description: 'De primaire sleutel van het gegeven in het bronsysteem'
        code:
          type: 'string'
          format: 'any'
          description: 'De unieke code (Bijvoorbeeld om te tonen of te zoeken)'
    ExtraAttribuut:
      type: object
      properties:
        naam:
          type: 'string'
          format: 'any'
          description: 'De naam van het niet bestaande attribuut. Bijv. Huurprognose.'
        waarde:
          type: 'string'
          format: 'any'
          description: 'De waarde van het niet bestaande attribuut. Bijv. €850,-.'
    Foutbericht:
      type: 'object'
      properties:
        code:
          type: 'string'
        omschrijving:
          type: 'string'

